services:
  protonmail-bridge:
    image: ghcr.io/enucatl/protonmail-bridge:3.23.1
    build:
      context: ./build
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["run"]
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - "10243:1243"
      - "10125:1125"
    volumes:
      - protonmail:/data
      - /opt/docker/traefik/data/certs/docker_key.pem:/data/config/protonmail/bridge-v3/key.pem:ro
      - /opt/docker/traefik/data/certs/docker_fullchain.pem:/data/config/protonmail/bridge-v3/cert.pem:ro
    labels:
      - "checkmk_monitor=true"

volumes:
  protonmail:
