services:
  protonmail-bridge:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-medium
    image: ghcr.io/enucatl/protonmail-bridge:3.24.1
    build:
      context: ./build
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["run"]
    ports:
      - "10243:1243"
      - "10125:1125"
    volumes:
      - protonmail:/data
      - /opt/docker/traefik/data/certs/docker_key.pem:/protonmail/certs/key.pem:ro
      - /opt/docker/traefik/data/certs/docker_fullchain.pem:/protonmail/certs/cert.pem:ro
    labels:
      - "checkmk_monitor=true"

  protonmail-bridge-init:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-medium
    image: ghcr.io/enucatl/protonmail-bridge:3.24.1
    build:
      context: ./build
      dockerfile: Dockerfile
    command: ["init"]
    profiles:
      - init
    stdin_open: true
    tty: true
    volumes:
      - protonmail:/data
      - /opt/docker/traefik/data/certs/docker_key.pem:/protonmail/certs/key.pem:ro
      - /opt/docker/traefik/data/certs/docker_fullchain.pem:/protonmail/certs/cert.pem:ro
volumes:
  protonmail:
